### ISSUE TITLE
vcfR2tidy: Columns must have unique names

### ISSUE THREAD

**Issue by igordot** [knausb/vcfR#95] opened 2018-03-16 03:00 UTC
I was able to import my VCF seemingly without problems.
```
> muts_vcfr = read.vcfR(my_vcf, verbose = TRUE)
Scanning file to determine attributes.
File attributes:
  meta lines: 81
  header line: 82
  variant count: 116
  column count: 11
Meta line 81 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 116
  Character matrix gt cols: 11
  skip: 0
  nrows: 116
  row_num: 0
Processed variant: 116
All variants processed
```
Then I tried to convert it to a data frame and got an error:
```
> vcfR2tidy(muts_vcfr)
Error: Columns `NT`, `SGT`, `MQ`, `MQ0`, `SOMATIC`, `SomaticEVS` must have unique names
```
The error is actually coming from `extract_info_tidy`:
```
> extract_info_tidy(muts_vcfr)
Error: Columns `NT`, `SGT`, `MQ`, `MQ0`, `SOMATIC`, `SomaticEVS` must have unique names
```

I think the problem might be that not all variants share all the fields. Is that possible? Is there a way to get around that?

**Comment by knausb** [comment] 2018-03-16 15:20
Hi @igordot, this sounds like [issue 91](https://github.com/knausb/vcfR/issues/91). Could you please check this and let me know if you're reporting the same issue? If you are, then you probably do not have the most current version of `vcfR`. Issue 91 was implemented on 2018-02-02.  And `vcfR` 1.7.0 was released on CRAN on 2018-02-07. Are you using the most current version? If this doesn't address your issue, perhaps you could use the example there to construct a minimal reproducible example? Thanks!
Brian

**Comment by igordot** [comment] 2018-03-16 15:43
I have the latest vcfR (1.7.0).

If you'd like to try yourself, I posted a small test VCF here: https://www.dropbox.com/s/xjyr1q3x685whlk/test.vcf?dl=0

**Comment by knausb** [comment] 2018-03-16 16:20
Excellent! I now see this.

```
vcf <- read.vcfR('test.vcf')
# I'll omit the output for read.vcfR() because it is not in question.
extract_info_tidy(vcf)
```
```
Error: Columns `NT`, `SGT`, `MQ`, `MQ0`, `SOMATIC`, `SomaticEVS` must have unique names
```

Which appears to reproduce the issue. I'll get to work on this. Thanks!
Brian

**Comment by igordot** [comment] 2018-03-16 18:28
I think I know what the problem is. Some of the `INFO` and `FORMAT` definitions in the header are duplicated.

You may be able to solve it by adding `dplyr::distinct(Tag, ID)` to `vcf_field_names()`. That may cause other issues, though.

**Comment by knausb** [comment] 2018-03-16 21:37
I think you are correct. We can see this as follows.

```
vcf <- read.vcfR('test.vcf')
queryMETA(vcf, element = '=NT')
```

```
[[1]]
[1] "INFO=ID=NT"                                          
[2] "Number=1"                                            
[3] "Type=String"                                         
[4] "Description=Genotype of the normal in all data tiers"
[5] " as used to classify somatic variants. One of {ref"  
[6] "het"                                                 
[7] "hom"                                                 
[8] "conflict}."                                          

[[2]]
[1] "INFO=ID=NT"                                          
[2] "Number=1"                                            
[3] "Type=String"                                         
[4] "Description=Genotype of the normal in all data tiers"
[5] " as used to classify somatic variants. One of {ref"  
[6] "het"                                                 
[7] "hom"                                                 
[8] "conflict}." 
```

This seems very odd to me. If both of these fields are identical, then the information is redundant. I can't think of a reason you would want this. If both fields are not identical and they have the same key ('NT') then I do not see any way to tell them apart. Can you explain to me why this would be a useful feature?

The error is thrown when we attempt to convert our data.frame of INFO into a tibble. The tibble does not want to have non-unique column names. And that sounds like a good thing to me because it may inform you that your data may have issues.

I've never seen this before. And it makes me concerned that you have a poorly form VCF file. Can you share with me what software created it? Can you explain why you would want this sort of data in your file? Have you tried to manually manipulate this file? Thanks!

**Comment by igordot** [comment] 2018-03-17 18:03
Yes, I do not want redundant information. This VCF was actually merged. According to `bcftools`, it was a valid VCF. Thus, I thought it was fine and did not bother checking in more depth.

After re-merging with Picard, I no longer get the error.

To summarize, this turned out to be a slightly malformed VCF. However, you may consider adding a specific check for this in case anyone else runs into the same problem.

**Comment by knausb** [comment] 2018-03-19 19:11
Hi @igordot, thanks for the clarification! We could create a function that queries the INFO and FORMAT keys in the meta lines and if it detects duplicates we can throw a warning such as what follows.

```
Warning message:
The following INFO key occurred more than once: MQ 
The following INFO key occurred more than once: MQ0 
The following INFO key occurred more than once: NT 
The following INFO key occurred more than once: SGT 
The following INFO key occurred more than once: SOMATIC 
The following INFO key occurred more than once: SomaticEVS 
```

We can leave it as a user callable function but also use it in `read.vcfR()` to test the keys for non-unique values. Does that sound like it would address your suggestion?

**Comment by igordot** [comment] 2018-03-19 22:05
That sounds good to me. Sounds very helpful.

**Comment by knausb** [comment] 2018-03-21 19:24
A function named `check_keys()` has been added at 74ab09fc0985bb4a4bc0d13645e9710f857eca58. The user can call it and it is called by `read.vcfR()` to help ensure a reasonable file has been read in. If you'd like to give it a try you can install the GitHub version.

```
devtools::install_github(repo="knausb/vcfR")
```

Note that this will require a compiler. This will be in the next release of vcfR to CRAN. So you can also just wait unttil then.

**Closed** 2018-03-23 01:01 UTC
