### ISSUE TITLE
Can't load vcf file

### ISSUE THREAD

**Issue by zillurbmb51** [knausb/vcfR#68] opened 2017-06-04 17:45 UTC
Sir,
I am new in using vcfR. I was trying to plot my vcf like , depth, quality etc. But, I can't load my vcf file. It shows: `> cow_vcf=read.vcfR("Cow.vcf", verbose=FALSE)
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`

What does the error mean? I have 10 vcf file for 10 organisms, generated by bowtie2, samtools and bcftools. I was able to load only 1 out 10 vcf file (all of these were produced by same pipeline). my files are too large (more than 100 gb) to upload. Thanks in advance.

Best Regards
Zillur

**Comment by knausb** [comment] 2017-06-04 23:14
Hi Zillur,

I have a few guesses, but I'll need a little more information in order to help you. Could you try the following.


```
vcf <- read.vcfR("smallvcf.vcf.gz", verbose = TRUE)
```

But using your file instead of the example I've used. The verbose setting will give me some information on what may be going on. It should look something like this:

```
Meta line 101 read in.
## All meta lines processed.
## Character matrix gt created.
## Character matrix gt rows: 4
## Character matrix gt cols: 40
## skip: 0
## nrows: 4
## row_num: 0
## 
## 
Processed variant: 4
## All variants processed
```

Could you also try this.

```
vcf <- read.vcfR("smallvcf.vcf.gz", verbose = TRUE, nrows = 10)
```

The `nrows` parameter will limit the number of rows (variants) read in. If you are successful you can use the `show` method to validate what you read in.

```
vcf
## ***** Object of Class vcfR *****
## 31 samples
## 1 CHROMs
## 10 variants
## Object size: 0 Mb
## 0 percent missing data
## *****        *****         *****
```

Lastly, could you provide your session info.

```
sessionInfo()
```

Could you please do this and copy and paste the results into a message? This should help me trouble shoot this. Thanks!

**Comment by zillurbmb51** [comment] 2017-06-05 01:40
Thank you very much for a quick reply. I created some small vcf using : `head -10000 cow.vcf > cow_10000.vcf`. Now they are loading. Here: `est_7=read.vcfR("opossum_10000.vcf", verbose=TRUE, nrows=10)
Meta line 5169 read in.
All meta lines processed.
Character matrix gt created.
Character matrix gt rows: 10
Character matrix gt cols: 10
skip: 0
nrows: 10
row_num: 0

Processed variant: 25
All variants processed`
 One vcf shows: `test_8=read.vcfR("orangutan_10000.vcf", verbose=TRUE, nrows=10)
Meta line 10000 read in.
All meta lines processed.
Character matrix gt created.
Character matrix gt rows: 10
Character matrix gt cols: 8
skip: 0
nrows: 10
row_num: 0

Warning: no header information was found! Data contains no sample names!
Processed variant: 0
All variants processed`
Then to view: ` test_10
***** Object of Class vcfR *****
1 samples
1 CHROMs
10 variants
Object size: 0.5 Mb
0 percent missing data
*****        *****         *****
> test_9
***** Object of Class vcfR *****
1 samples
1 CHROMs
10 variants
Object size: 0.4 Mb
0 percent missing data`
and session info: `> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] vcfR_1.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11      lattice_0.20-34   ape_4.1           viridisLite_0.2.0
 [5] permute_0.9-4     memuse_3.0-1      MASS_7.3-45       grid_3.3.3       
 [9] nlme_3.1-131      magrittr_1.5      vegan_2.4-3       Matrix_1.2-8     
[13] pinfsc50_1.1.0    tools_3.3.3       parallel_3.3.3    cluster_2.0.5    
[17] mgcv_1.8-17  `
Thanks again.

Best Regards
Zillur

**Comment by knausb** [comment] 2017-06-05 17:32
Hi Zillur,

When you call `read.vcfR()` it scans through your file to determine how many columns (samples) and rows (variants) are in it. It then uses this information to initialize a data structure to hold this data. As a programmer I need to use a container to hold this count information. Because different containers can hold different amounts of data, I have to make a guess as to what sort of container is suitable. The size of containers varies among systems. You can see a discussion of this [here](https://stackoverflow.com/a/589684). When you exceed the size of a signed container, it rolls over to a negative number and starts incrementing again. I think this is why your error message is complaining `negative length vectors are not allowed`. When you used the `nrows` parameter you circumvent this behavior. In order to validate that this is the issue I think we need a little more information about your file. If you could try the `read.vcfR()` with the verbose setting set to TRUE it should report how many rows and columns it thinks are in the file. If you could copy and paste this info into a message it would help me.

Also, you appear to be using a Unix system, so we can validate how many lines are in your file at the shell.

```
wc -l cow.vcf
```

Should tell you the number of lines that are in your file. You can then use:

```
grep -c "^##"
```

to count the number of meta lines (the meta lines begin with ##). This will tell you how many of the lines are meta. So the number of variants in your file should be the results of `wc -l` minus `grep -c "^##"` minus one (there is one header line). If you could report these values to me it will help me validate if my suspicions here are true.

Thanks!
Brian

**Comment by zillurbmb51** [comment] 2017-06-05 18:14
Thank you very much for your reply. I also think size may cause the problem as my files are 200-300  gb each. To parse these take too much time, even "wc -l". However, I am working on this and giving you all the information as soon as possible.

Best Regards
Zillur

**Comment by knausb** [comment] 2017-06-07 17:15
Hi Zillur,

I've created a documentation on VCF file size and memory estimation at:

https://knausb.github.io/vcfR_documentation/how_much_memory.html

Perhaps this will help you?
Brian

**Comment by zillurbmb51** [comment] 2017-06-08 13:53
thank you very much sir. The documentation is really useful. Here is the error message when I set verbose=TRUE.
`> sheep_vcf=read.vcfR("Sheep.vcf", verbose=TRUE)
Meta line 5498 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed
`
`> pig_vcf=read.vcfR("Pig.vcf", verbose=TRUE)
Meta line 4615 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`
`> orangutan_vcf=read.vcfR("Orangutan.vcf", verbose=TRUE)
Meta line 61570 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`
`> opossum_vcf=read.vcfR("Opossum.vcf", verbose=TRUE)
Meta line 5169 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`
`> nakemolerat_vcf=read.vcfR("NakedMoleRat.vcf", verbose=TRUE)
Meta line 4261 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`
`> horse_vcf=read.vcfR("HorseAnn.vcf", verbose=TRUE)
Meta line 9674 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`

**Comment by knausb** [comment] 2017-06-08 16:48
Hi Zillur,

Thanks for sticking with me on this! However, without a minimal reproducible example for me to reproduce your reported behaviour on my local machine, all I can do is guess. Right now my best guess is that `read.vcfR` seems to **think** that you have a negative number of variants (rows). My best guess for this is that your file has exceeded the size of the counter I've used. I think the best way to validate the number of variants in the file. Above I asked you to report the results of:

```
wc -l cow.vcf
grep -c "^##" cow.vcf
```

and you stated you were working on this. Could you post the results from these commands in your next message?

Thanks!
Brian

**Comment by zillurbmb51** [comment] 2017-06-08 17:01
Thank you very much for reminding me this. Here it is, command for 1st output: "wc -l cow.vcf > cow_line.txt" and for 2nd output: "grep -c "^##" cow.vcf | wc -l > cow_meta.txt" . Maybe in the 2nd command I don't need to pipe it. so it was a mistake. I am running again the grep and will report to you soon. 

`[zillur@genomics ~]$ more /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/*
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/bunny_lines.txt
::::::::::::::
2586897062 ../../vcfs/Bunny.vcf
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/bunny_meta.txt
::::::::::::::
1
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/cow_line.txt
::::::::::::::
2625557698 ../../vcfs/Cow.vcf
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/cow_meta.txt
::::::::::::::
1
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/elephant_line.t::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/elephant_line.txt
::::::::::::::
3060975581 ../../vcfs/Elephant.vcf
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/elephant_meta.t::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/elephant_meta.txt
::::::::::::::
1
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/gorilla_line.tx::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/gorilla_line.txt
::::::::::::::
200073615 ../../vcfs/Gorilla.vcf
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/gorilla_meta.tx::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/gorilla_meta.txt
::::::::::::::
1
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/horse_line.txt
::::::::::::::
2417483592 ../../vcfs/HorseAnn.vcf
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/horse_meta.txt
::::::::::::::
1
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/nakedmolerat_li::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/nakedmolerat_line.txt
::::::::::::::
2280297137 ../../vcfs/NakedMoleRat.vcf
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/nakedmolerat_me::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/nakedmolerat_meta.txt
::::::::::::::
1
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/opossum_line.tx::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/opossum_line.txt
::::::::::::::
3479688177 ../../vcfs/Opossum.vcf
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/opossum_meta.tx::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/opossum_meta.txt
::::::::::::::
1
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/orangutan_line.::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/orangutan_line.txt
::::::::::::::
3028665585 ../../vcfs/Orangutan.vcf
--More--(Next file: /gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/orangutan_meta.::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/orangutan_meta.txt
::::::::::::::
1
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/pig_line.txt
::::::::::::::
2464897162 ../../vcfs/Pig.vcf
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/pig_meta.txt
::::::::::::::
1
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/sheep_line.txt
::::::::::::::
2544104361 ../../vcfs/Sheep.vcf
::::::::::::::
/gondor/zillur/bodysize_analysis/test_vcfs/vcf_info/sheep_meta.txt
::::::::::::::
1
`

Thanks again.
Best Regards
Zillur

**Comment by zillurbmb51** [comment] 2017-06-09 14:18
Here is the output of grep; The command is:
`grep -c "^##" ../vcf_folder/*.vcf > meta_all.txt`
The output:

`[zillur@genomics vcf_info]$ more meta_all.txt 
../../snpeff_analysis/bunny.ann.vcf:3278
../../snpeff_analysis/cow.ann.vcf:3181
../../snpeff_analysis/elephant.ann.vcf:2389
../../snpeff_analysis/gorilla.ann.vcf:40748
../../snpeff_analysis/horse.ann.vcf:9678
../../snpeff_analysis/orangutan.ann.vcf:61575
../../snpeff_analysis/pig.ann.vcf:4620
../../snpeff_analysis/sheep.ann.vcf:5503
`

Best Regards
Zillur

**Comment by knausb** [comment] 2017-06-09 16:16
Hi Zillur,

Thanks for reporting the results from those commands, it really helps! Let's recap. You're trying to read in VCF files that range in size from 200,073,615 to 3,479,688,177 lines in size. Based on the information posted [here](https://knausb.github.io/vcfR_documentation/how_much_memory.html) you'd need around 6.4 Tb of RAM to read in 100 million variants. So its not practical for you to expect to read the entire file into memory. However the problem does not appear to be that you're trying to allocate more RAM than your system has. Instead there appears to be a value that is being reported as negative when it shouldn't be negative. My best guess at the present is that for some reason the number of variants is being interpreted as negative. When asked to read in subsets of the data the poster reported success, which I feel reinforces my suspicion.

In the above messages it appears that the posting party is using CentOS. This suggests that they have a compiler available to them so I can ask them to perform tests that require a compiler.

The function `vcfR_read_body_gz` uses an `Rcpp::NumericVector` to count the number of variants in the file (and other attributes). It is possible that this container has exceeded its maximum value and has rolled over to negative numbers. Now that I have a better idea of how many lines are in the files this does not seem so reasonable. But we can test this to make sure. Could you copy and paste the below code into your R session?

```
library(Rcpp)
cppFunction('void counter() {
  Rcpp::NumericVector stats(4);
  for(stats(2) = 1000000000; stats(2) <= 4000000000; stats(2) = stats(2) + 100000 ){
    Rcpp::Rcout << "Counter at: ";
    Rcpp::Rcout << stats(2);
    Rcpp::Rcout << std::endl;
  }
}')
counter()
```

This will compile a program that increments elements in an `Rcpp::NumericVector`. Output on my machine includes many lines, the last of which are:

```
Counter at: 3.9996e+09
Counter at: 3.9997e+09
Counter at: 3.9998e+09
Counter at: 3.9999e+09
Counter at: 4e+09
```

The important issue here is that we reached 4 million and that this value is positive. This validates that our container did not exceed its maximum value. Can you post the last few lines of your output to validate that they are similar?

Assuming you get similar results to those I have, it means we have not isolated the issue. I've updated the master branch at GitHub so the `read.vcfR()` generated verbose output that is more verbose than the version posted at CRAN. Could you install this version and report the output generated by `read.vcfR()` with `verbose = TRUE` for me?

```
devtools::install_github(repo="knausb/vcfR")
```

This would give me a better idea of how vcfR 'sees' the data and whether I'm on the right track.

Thanks!
Brian

**Comment by zillurbmb51** [comment] 2017-06-09 18:05
Thank you very much for your comment. Here is the output of the counter function:
`Counter at: 3.998e+09
Counter at: 3.9981e+09
Counter at: 3.9982e+09
Counter at: 3.9983e+09
Counter at: 3.9984e+09
Counter at: 3.9985e+09
Counter at: 3.9986e+09
Counter at: 3.9987e+09
Counter at: 3.9988e+09
Counter at: 3.9989e+09
Counter at: 3.999e+09
Counter at: 3.9991e+09
Counter at: 3.9992e+09
Counter at: 3.9993e+09
Counter at: 3.9994e+09
Counter at: 3.9995e+09
Counter at: 3.9996e+09
Counter at: 3.9997e+09
Counter at: 3.9998e+09
Counter at: 3.9999e+09
Counter at: 4e+09`

Loading vfcs with the new version, I will report as soon as I get something.

Best Regards
Zillur

**Comment by knausb** [comment] 2017-06-09 18:58
This validates that the container is behaving appropriately on both of our machines and that it appears to be an appropriate tool for the task required of it. It will be interesting to see what teh verbose output of `read.vcfR()` is. 

Thanks Zillur!
Brian

**Comment by zillurbmb51** [comment] 2017-06-13 15:15
Thank you very much sir. Here is the output from new version:
`> bunny_vcf=read.vcfR("bunny.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 3278
  header line: 3279
  variant count: 2586893788
  column count: 10
Meta line 3278 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed
`

`> cow_vcf=read.vcfR("cow.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 3181
  header line: 3182
  variant count: 2625554521
  column count: 10
Meta line 3181 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`

`> elephant_vcf=read.vcfR("elephant.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 2389
  header line: 2390
  variant count: 2933713396
  column count: 10
Meta line 2389 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`

`> gorilla_vcf=read.vcfR("gorilla.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 40748
  header line: 40749
  variant count: 200032871
  column count: 10
Meta line 40748 read in.
All meta lines processed.
Character matrix gt created.
Character matrix gt rows: 200032871
Character matrix gt cols: 10
skip: 0
nrows: 200032871
row_num: 0

Processed variant: 200032871
All variants processed`


`> horse_vcf=read.vcfR("horse.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 9678
  header line: 9679
  variant count: 2417473917
  column count: 10
Meta line 9678 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`

`> orangutan_vcf=read.vcfR("orangutan.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 61575
  header line: 61576
  variant count: 2898508467
  column count: 10
Meta line 61575 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`

`> pig_vcf=read.vcfR("pig.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 4620
  header line: 4621
  variant count: 2464892546
  column count: 10
Meta line 4620 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed`

`> sheep_vcf=read.vcfR("sheep.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 5503
  header line: 5504
  variant count: 2544098862
  column count: 10
Meta line 5503 read in.
All meta lines processed.
Error in .Call("vcfR_read_body_gz", PACKAGE = "vcfR", file = file, stats = stats,  : 
  negative length vectors are not allowed
`

Best regards
Zillur

**Comment by knausb** [comment] 2017-06-13 20:18
It appears you have a relatively small file, gorilla.ann.vcf, that you are successful at opening. It has 200,032,871 variants. The next largest file, horse.ann.vcf, has 2,417,473,917 and you are producing a negative length vector error. All files have only one samples (10 columns). Note that the variant number is reported as positive and not negative as I had suspected. This means I currently do not have a good guess as to where this issue is located.

Based off of the above information I have used *.g.vcf.gz files from a project I'm working on to try to reproduce the problem. I do not have files with as many variants so I've concatenated files together to generate files of comparable size. A first step used a file with just over a billion variants.

```
> vcf <- read.vcfR("onebillion.vcf.gz")
File attributes:
  meta lines: 5014
  header line: 5015
  variant count: 1096715660
  column count: 10
Meta line 5014 read in.
All meta lines processed.
Error: cannot allocate vector of size 81.7 Gb
```

I interpret this as appropriate behaviour. The error is informing us that we can't create a large vector. This is now an issue that is outside of `vcfR` which I have no control of. And the error appears meaningful. This is why I interpret this as reasonable behaviour.

When I double the file size I get the following.

```
> vcf <- read.vcfR("twobillion.vcf.gz")
File attributes:
  meta lines: 5014
  header line: 5015
  variant count: 2193431320
  column count: 10
Meta line 5014 read in.
All meta lines processed.
Error in read.vcfR("twobillion.vcf.gz") : 
  negative length vectors are not allowed
```

This appears to be the error reported. Now that I have a reproducible example I can work to narrow this issue down. However, because it takes a bit to process the file, it will probably be a bit before I have a solution. We'll get there. Thanks Zillur!

**Comment by knausb** [comment] 2017-06-13 22:22
The issue is that we have rolled over the maximum value of an `int`. Some thresholds for containers can be seen [at this link](https://en.wikibooks.org/wiki/C_Programming/limits.h). The `Rcpp::NumericVector` used to hold stats on the vcf file appears to accommodate this. But in the C++ function `vcfR_read_body_gz` (not exported to the user) an `int` has been used to hold row numbers. This probably topped out at +2,147,483,647 and rolled over to −2,147,483,648 (may be system dependent). I've changed these to `long int`s to accommodate these values.

This does not appear to have resolved the issue. It appears that a `Rcpp::CharacterMatrix`, the container used to hold the body of the VCF data. tops out at this value as well. This can be illustrated with a little program.

```
library(Rcpp)
cppFunction('Rcpp::CharacterMatrix mkMatrix( long int nrows, long int ncols){

  // NA matrix for unexpected results.
  Rcpp::StringMatrix na_matrix(1,1);
  na_matrix(0,0) = NA_STRING;

  if( nrows > INT_MAX ){
    Rcpp::Rcerr << "Requested a matrix of " << nrows << " rows." << std::endl;
    Rcpp::Rcerr << "This exceeds INT_MAX, which is " << INT_MAX << "." << std::endl;
    Rcpp::Rcerr << "I suggest you attempt to read in a portion of the file using the options nrows and skip." << std::endl;
    return na_matrix;
  }

  Rcpp::Rcout << "nrows: " << nrows << std::endl;
  Rcpp::Rcout << "ncols: " << ncols << std::endl;
  Rcpp::CharacterMatrix gt( nrows, ncols );
  return gt;
}')
mkMatrix(2,4)
myMat <- mkMatrix(2147483647,4)
myMat <- mkMatrix(2147483648,4) # Negative vector error
```

I've added the above example for handling this behaviour to the function `vcfR_read_body_gz` in an attempt to provide a more meaningful error message and to propose a work around. So I think we've caught the error and handled it. 

This update is now on the master branch at GitHub and can be installed as follows.

```
devtools::install_github(repo="knausb/vcfR")
```

I think we're ready to close this. What do you think @zillurbmb51?

**Comment by zillurbmb51** [comment] 2017-06-15 17:18
Thank you sir for helping me all the way. Here is the outputs after latest version:
`> bunny_vcf=read.vcfR("bunny.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 3278
  header line: 3279
  variant count: 2586893788
  column count: 10
Meta line 3278 read in.
All meta lines processed.
Error in read.vcfR("bunny.ann.vcf", verbose = TRUE) : 
  negative length vectors are not allowed
`

`> horse_vcf=read.vcfR("horse.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 9678
  header line: 9679
  variant count: 2417473917
  column count: 10
Meta line 9678 read in.
All meta lines processed.
Error in read.vcfR("horse.ann.vcf", verbose = TRUE) : 
  negative length vectors are not allowed
`

`> orangutan_vcf=read.vcfR("orangutan.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 61575
  header line: 61576
  variant count: 2898508467
  column count: 10
Meta line 61575 read in.
All meta lines processed.
Error in read.vcfR("orangutan.ann.vcf", verbose = TRUE) : 
  negative length vectors are not allowed
`

`> pig_vcf=read.vcfR("pig.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 4620
  header line: 4621
  variant count: 2464892546
  column count: 10
Meta line 4620 read in.
All meta lines processed.
Error in read.vcfR("pig.ann.vcf", verbose = TRUE) : 
  negative length vectors are not allowed`

`> sheep_vcf=read.vcfR("sheep.ann.vcf", verbose=TRUE)
File attributes:
  meta lines: 5503
  header line: 5504
  variant count: 2544098862
  column count: 10
Meta line 5503 read in.
All meta lines processed.
Error in read.vcfR("sheep.ann.vcf", verbose = TRUE) : 
  negative length vectors are not allowed
`

What should I do now?

Best Regards
Zillur

**Comment by knausb** [comment] 2017-06-16 15:29
Hi @zillurbmb51, I think you have not updated to the latest version. You can do so with:

```
devtools::install_github(repo="knausb/vcfR")
library(vcfR)
```

When I try to load a VCF file of similar size to those you reported I get.

```
> vcf <- read.vcfR("twobillion.vcf.gz")
File attributes:
  meta lines: 5014
  header line: 5015
  variant count: 2193431320
  column count: 10
Meta line 5014 read in.
All meta lines processed.
In function read_body_gz.
  stats(0): 5014
  stats(1): 5015
  stats(2): 2.19343e+09
  stats(3): 10
Initializing gt matrix.
  nrows: 2193431320
  cols.size(): 10
Requested a matrix of 2193431320 rows.
This exceeds INT_MAX, which is 2147483647.
I suggest you attempt to read in a portion of the file using the options 'nrows' and 'skip'.
Error in body[, 1:8, drop = FALSE] : subscript out of bounds
```

Note that this is not an attempt to help you read the file in. Instead its an attempt to help you understand *why* you can't. You can use the `memuse` package to estimate R object sizes. For your sheep example above I get the following.

```
> memuse::howbig(nrow = 2544098862, ncol=10)
189.550 GiB
```

Unless the computer you're working on has around 200 GB of memory, there's no way to read this file into memory. You'll need to develop strategies to subset the file. The function `read.vcfR()` has subsetting options to help with this.

```
> vcf <- read.vcfR("twobillion.vcf.gz", nrows = 1000000, skip = 2000000)
```

Should read in variants 2000000:3000000.

Also, I suggest dividing your VCF files into subsets to improve access times. I've posted some documentation on [how to divide VCF files here](https://knausb.github.io/vcfR_documentation/subset_data_to_1chrom.html).

**Comment by knausb** [comment] 2017-06-21 21:52
This thread appears to have gone stale. I'd like to close it. What do you think @zillurbmb51?

**Comment by zillurbmb51** [comment] 2017-06-23 20:21
Yeah. Sure. Thank you very much for helping me all the time. After subsetting if I face any problem, I will let you know.

Best Regards
Zillur

**Comment by knausb** [comment] 2017-06-23 20:25
Thank you for helping improve vcfR! And yes, please let me know if you have any other problems.
Brian

**Closed by knausb** 2017-06-23 20:25 UTC
